const K='gmcBatch';let data=null;const $=id=>document.getElementById(id);
const words={vi:{language:'Ngôn ngữ',intro:'Quy trình hai pha: chốt danh sách trước, sau đó lấy chi tiết từng địa điểm.',phase1Title:'1. Tạo danh sách',keyword:'Từ khóa',keywordExample:'Ví dụ: khách sạn',area:'Khu vực',areaExample:'Mỗi dòng một địa chỉ đầy đủ, ví dụ:\nĐường Mai Chí Thọ, Thành phố Thủ Đức, TP. Hồ Chí Minh, Việt Nam',areaHelp:'Mỗi dòng là một khu vực/địa chỉ. Dấu phẩy là một phần của địa chỉ và sẽ được giữ nguyên.',runPhase1:'Chạy pha 1 · Cào danh sách',exportPhase1:'Xuất danh sách pha 1',phase2Title:'2. Lấy thông tin chi tiết',phase2Help:'Mở trực tiếp từng địa điểm để lấy địa chỉ, website, số điện thoại, tọa độ.',runPhase2:'Chạy pha 2 · Lấy chi tiết',exportDetails:'Xuất CSV chi tiết',stop:'Dừng',clear:'Xóa toàn bộ dữ liệu'},zh:{language:'语言',intro:'两阶段流程：先确定列表，再逐项获取详细信息。',phase1Title:'1. 创建列表',keyword:'关键词',keywordExample:'例如：酒店',area:'区域',areaExample:'每行一个完整地址，例如：\nMai Chí Thọ 街，守德市，胡志明市，越南',areaHelp:'每一行代表一个区域或地址；地址中的逗号会被保留。',runPhase1:'运行阶段 1 · 收集列表',exportPhase1:'导出阶段 1 列表',phase2Title:'2. 获取详细信息',phase2Help:'直接打开每个地点以获取地址、网站、电话和坐标。',runPhase2:'运行阶段 2 · 获取详情',exportDetails:'导出详情 CSV',stop:'停止',clear:'清除全部数据'}};
function setLanguage(lang){const text=words[lang]||words.vi;document.documentElement.lang=lang==='zh'?'zh-CN':'vi';document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=text[e.dataset.i18n]||e.textContent);document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>e.placeholder=text[e.dataset.i18nPlaceholder]||e.placeholder);chrome.storage.local.set({gmcLanguage:lang});}
document.addEventListener('DOMContentLoaded',async()=>{for(const id of['phase1','phase2','stop','export','export-phase1','clear'])$(id).addEventListener('click',actions[id]);chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&c[K]){data=c[K].newValue;render();}});const stored=await chrome.storage.local.get([K,'gmcLanguage']);data=stored[K]||null;$('language').value=stored.gmcLanguage||'vi';$('language').onchange=e=>setLanguage(e.target.value);setLanguage($('language').value);render();});
const actions={
  phase1:async()=>{const keyword=$('keyword').value.trim(),areas=[...new Set($('areas').value.split(/\r?\n|;/).map(x=>x.trim()).filter(Boolean))];if(!keyword||!areas.length)return alert('Nhập từ khóa và ít nhất một khu vực.');await send({action:'START_PHASE1',keyword,areas});},
  phase2:()=>send({action:'START_PHASE2'}),stop:()=>send({action:'STOP_BATCH'}),
  export:()=>download(Object.values(data?.resultsByArea||{}).flat(),'gmaps_chi-tiet.csv'),
  'export-phase1':()=>download(Object.values(data?.phase1ByArea||{}).flat(),'gmaps_danh-sach.csv'),
  clear:async()=>{if(data?.status==='running')return alert('Hãy dừng lượt chạy trước khi xóa dữ liệu.');if(!confirm('Xóa toàn bộ danh sách, dữ liệu chi tiết và tiến độ đã lưu?'))return;await chrome.storage.local.remove(K);data=null;render();}
};
async function send(message){const result=await chrome.runtime.sendMessage(message);if(!result?.ok)alert(result?.error||'Không thể thực hiện thao tác.');}
function render(){const s=data||{},areas=s.areas||[],one=s.phase1ByArea||{},two=s.resultsByArea||{},phase=s.phase||'ready',total=areas.reduce((n,a)=>n+(one[a]?.length||0),0),done=Object.values(two).flat().filter(Boolean).length,running=s.status==='running';$('message').textContent=s.message||'Sẵn sàng';$('counts').textContent=`Pha 1: ${total} địa điểm đã chốt · Pha 2: ${done}/${total} địa điểm đã lấy chi tiết`;$('phase1').disabled=running;$('phase2').disabled=running||!total;$('export-phase1').disabled=!total;$('export').disabled=!done;$('clear').disabled=running;const p=phase==='phase2'&&total?done/total:areas.length?(s.completedAreas?.length||0)/areas.length:0;$('progress').style.width=`${p*100}%`;$('list').innerHTML=areas.map(a=>`<div class="row"><b>${escape(a)}</b><span>Danh sách: ${one[a]?.length||0} · Chi tiết: ${two[a]?.filter(Boolean).length||0}</span></div>`).join('')||'<span class="muted">Chưa có dữ liệu.</span>';if(s.keyword)$('keyword').value=s.keyword;if(areas.length)$('areas').value=areas.join('\n');}
function download(rows,name){if(!rows.length)return;const cols=[['name','Name'],['address','Address'],['plusCode','PlusCode'],['website','Website'],['url','GoogleMapsURL'],['rating','Rating'],['phone','Phone'],['coordinates','Coordinates']],lines=[cols.map(x=>x[1]).join(',')];for(const row of rows)lines.push(cols.map(([key])=>cell(row[key])).join(','));const url=URL.createObjectURL(new Blob(['\uFEFF',lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));chrome.downloads.download({url,filename:name,saveAs:false});setTimeout(()=>URL.revokeObjectURL(url),10000);}
function cell(value){let text=String(value??'');if(/^[=+@\-\t\r]/.test(text))text=`'${text}`;return`"${text.replace(/"/g,'""')}"`;}function escape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
